test:
	@python -u $$SVUT/svutRun.py -f files.f

test-dry-run:
	@python -u $$SVUT/svutRun.py -f files.f -dry-run

gui:
	@python -u $$SVUT/svutRun.py -f files.f -gui

clean:
	@-rm -f *.vcd
	@-rm -f *.lxt*
	@-rm -f *.vvp*
	@-rm -f *.out

